### PR TITLE
Custom markers fix

### PR DESCRIPTION
**Pull request by duxan**
Two source files changed. Compiled to `JSARToolKit.js` with provided script and minimized.

To test custom markers I used [this old tool](http://flash.tarotaro.org/blog/2008/12/14/artoolkit-marker-generator-online-released/)

Cheers!

### CODE REVIEW

**Comment by kig** [comment]
Thanks man, massive props!

**Comment by duxan** [comment]
I-m glad I could help. Btw. great library! It saved my HTML5 mobile project.

I-m testing it on Android (Cordova, Three.js and awesome [CROSSWALK](https://crosswalk-project.org/) webView, so webGL is no longer problem). 

Hope to have something soon to show :)

**Comment by dimpapadop** [comment]
hallo guys.
Dear @duxan can you please tell me how to identify custom markers, after i create them?
I am a bit confused, no documentation found.

for tracking the built-in markers and their ID i use...
  var thresholdAmount = 128; 
  detected = detector.detectMarkerLite(raster, thresholdAmount);
  select('#markersDetected').elt.innerText = detected;
  for (var i = 0; i < detected; i++) {
    // read data from the marker
    var id = detector.getIdMarkerData(i);
    //text("id[", i, "]="+id.getPacketData(i),10,10);
        var currId;
        if (id.packetLength > 4) {
          currId = -1;
        }else{
          currId=0;
          //παίρνω το ID του marker
          for (var ixx = 0; ixx < id.packetLength; ixx++ ) {
            currId = (currId << 8) | id.getPacketData(ixx);
            //console.log("id[", i, "]=", id.getPacketData(i));
          }
        }
        console.log("[add] : ID = " + currId);

How about custom ones? where will i place the pat files? what'll be their ID and how could i track them?

thanks in advance

**Comment by ioarvanit** [comment]
I have the same issue here. I can't understand how to identify a custom marker from a .pat file

Do i have to compile something first or run a script so that it can be identified and get an id?

**Comment by kalwalt** [comment]
@dimpapadop @ioarvanit if you are still interested you can find a custom marker example in my repo https://github.com/kalwalt/JSARToolKit/blob/master/demos/tests/test6.html

**Pull request merged**
